# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0059_skintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skintype',
            name='color',
            field=models.IntegerField(default=1),
        ),
    ]
