# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0060_auto_20170819_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='skincolor',
            field=models.IntegerField(default=1),
        ),
    ]
