# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0061_userinfo_skincolor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkinType',
        ),
    ]
